version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password123
    volumes:
      - cache:/data
  session-management:
    image: session-management:0.0.1
    ports:
      - '3000:3000'
    depends_on:
      - cache
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: password123
volumes:
  cache:
    driver: local
